"""empty message

Revision ID: cadabf01543a
Revises: 7b341695f43f
Create Date: 2022-11-03 16:57:09.231778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadabf01543a'
down_revision = '7b341695f43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nombre', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('apellidos', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apellidos')
    op.drop_column('user', 'nombre')
    # ### end Alembic commands ###
